theme: jekyll-theme-architect 

show_downloads: true

title: Text Case Converter-Editor

description: A Small Utility Made Using Python For Quickly Editing Text Cases Comes Handy When Dealing With Large Text ..
